execution provider set in quantization/image_classification/cpu/run.py
Set execution provider explicitly as required since ORT 1.0

ValueError: This ORT build has ['CUDAExecutionProvider', 'DnnlExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['CUDAExecutionProvider', 'DnnlExecutionProvider', 'CPUExecutionProvider'], ...)